<?php

declare(strict_types=1);

namespace FGTCLB\OAuth2Server\Tests\Functional;

use FGTCLB\OAuth2Server\Tests\Functional\AbstractTestCase;

class OAuthServerTest extends AbstractTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function oauthServerGrantsAccess(): void
    {
    }
}
