services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\OAuth2Server\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Entity/*'

  FGTCLB\OAuth2Server\Domain\Repository\ClientRepository:
    public: true
