name: tests11i3

on:
  push:
  pull_request:
  schedule:
    - cron:  '42 5 * * *'

jobs:
  testsuite:
    name: all tests
    runs-on: ubuntu-latest
    strategy:
      # This prevents cancellation of matrix job runs, if one or more already failed
      # and let the remaining matrix jobs be executed anyway.
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2', '8.3' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Link docker compose"
        run: |
          echo "#!/usr/bin/env bash" > /usr/local/bin/docker-compose
          echo "" >> /usr/local/bin/docker-compose
          echo "docker compose \"\$@\"" >> /usr/local/bin/docker-compose
          chmod a+x /usr/local/bin/docker-compose

      - name: Install dependencies
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s composerUpdate

      - name: Composer validate
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s composerValidate

      - name: Lint PHP
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s lint

      - name: CGL
        # php-cs-fixer has isues with php8.2, so avoid executing it with that php version.
        if: ${{ matrix.php <= '8.1' }}
        run: Build/Scripts/runTests.sh -t 11i3 -n -p ${{ matrix.php }} -s cgl

      - name: phpstan
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s phpstan -e "--error-format=github"

      - name: Unit Tests
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s unit

      - name: Functional Tests with mariadb and mysqli
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -d mariadb -a mysqli -s functional

      - name: Functional Tests with mariadb and pdo_mysql
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -d mariadb -a pdo_mysql -s functional

      - name: Functional Tests with mysql and mysqli
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -d mysql -a mysqli -s functional

      - name: Functional Tests with mysql and pdo_mysql
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -d mysql -a pdo_mysql -s functional

      - name: Functional Tests with postgres
        # v11 postgres functional disabled with PHP 8.2 since https://github.com/doctrine/dbal/commit/73eec6d882b99e1e2d2d937accca89c1bd91b2d7
        # is not fixed in doctrine core v11 doctrine 2.13.9
        if: ${{ matrix.php <= '8.1' }}
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -d postgres -s functional

      - name: Functional Tests with sqlite
        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -d sqlite -s functional

#      - name: Acceptance Tests mariadb and mysqli
#        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s acceptance -d mariadb -a mysqli
#
#      - name: Acceptance Tests mariadb and pdo_mysql
#        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s acceptance -d mariadb -a pdo_mysql
#
#      - name: Acceptance Tests mysql and mysqli
#        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s acceptance -d mysql -a mysqli
#
#      - name: Acceptance Tests mysql and pdo_mysql
#        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s acceptance -d mysql -a pdo_mysql
#
#      - name: Acceptance Tests postgres
#        # v11 postgres acceptance disabled with PHP 8.2 since https://github.com/doctrine/dbal/commit/73eec6d882b99e1e2d2d937accca89c1bd91b2d7
#        # is not fixed in doctrine core v11 doctrine 2.13.9
#        if: ${{ matrix.php <= '8.1' }}
#        run: Build/Scripts/runTests.sh -t 11i3 -p ${{ matrix.php }} -s acceptance -d postgres
